import { test } from 'node:test';
import assert from 'node:assert/strict';
import { drawActivity, filterActivities, searchActivities } from '../src/utils/activities';
import { defaultFilters, type Activity, type Filters } from '../src/types';
const base: Activity = { id: 'a', title: 'Criar uma colagem', category: 'Criar', duration: 15, cost: 0, places: ['casa'], company: ['sozinho', 'acompanhado'], image: 1, description: '', materials: [], steps: [] };
const catalog: Activity[] = [base, { ...base, id: 'b', title: 'Fotografar a praça', category: 'Movimentar', duration: 30, cost: 20, places: ['fora'], company: ['acompanhado'] }, { ...base, id: 'c', title: 'Café com amigos', category: 'Socializar', duration: 120, cost: 50, places: ['casa', 'fora'] }];
const unlimited: Filters = { time: null, budget: null, place: 'todos', company: 'todos' };
test('valores iniciais limitam a 60 minutos e custo zero', () => assert.deepEqual(filterActivities(catalog, defaultFilters).map(a => a.id), ['a']));
test('limites de tempo e custo são inclusivos e cumulativos', () => assert.deepEqual(filterActivities(catalog, { ...unlimited, time: 30, budget: 20, place: 'fora', company: 'acompanhado' }).map(a => a.id), ['b']));
test('grátis significa zero, não até 20', () => assert.deepEqual(filterActivities(catalog, { ...unlimited, budget: 0 }).map(a => a.id), ['a']));
test('sem limite de tempo não desativa orçamento', () => assert.equal(filterActivities(catalog, { ...unlimited, budget: 20 }).length, 2));
test('sem limite de orçamento não desativa tempo', () => assert.equal(filterActivities(catalog, { ...unlimited, time: 15 }).length, 1));
test('tanto faz e sem limite permitem todo o catálogo', () => assert.equal(filterActivities(catalog, unlimited).length, 3));
test('listas aceitam local e companhia múltiplos', () => assert.deepEqual(filterActivities(catalog, { ...unlimited, place: 'fora', company: 'sozinho' }).map(a => a.id), ['c']));
test('busca ignora caixa, espaços externos e acentos', () => assert.equal(searchActivities(catalog, ' CAFE ')[0]?.id, 'c'));
test('categoria e busca são cumulativas', () => assert.equal(searchActivities(catalog, 'colagem', 'Socializar').length, 0));
test('busca usa apenas o título', () => assert.equal(searchActivities([{ ...base, description: 'palavra secreta' }], 'secreta').length, 0));
test('sorteio vazio não retorna atividade', () => assert.equal(drawActivity([]), undefined));
test('sorteio com única opção permite repetir', () => assert.equal(drawActivity([base], base.id)?.id, base.id));
test('sorteio evita a última atividade entre candidatas', () => { for (let n = 0; n < 100; n++) assert.notEqual(drawActivity(catalog, 'a')?.id, 'a'); });
test('última atividade fora das candidatas não elimina opções', () => assert.equal(drawActivity(catalog, 'ausente', () => 0)?.id, 'a'));
test('sorteio respeita filtros, busca e categoria', () => { const list = searchActivities(filterActivities(catalog, { ...unlimited, budget: 20 }), 'praca', 'Movimentar'); assert.equal(drawActivity(list)?.id, 'b'); });
test('operações não alteram o catálogo', () => { const before = JSON.stringify(catalog); filterActivities(catalog, defaultFilters); searchActivities(catalog, 'a'); drawActivity(catalog, 'a'); assert.equal(JSON.stringify(catalog), before); });
