import { test } from 'node:test';
import assert from 'node:assert/strict';
import { emptyState, sanitizeState } from '../src/utils/savedState';
import { defaultFilters } from '../src/types';
const ids = new Set(['a', 'b']);
test('conteúdo ausente ou inesperado usa valores iniciais', () => { for (const value of [null, undefined, [], 'texto', 8]) assert.deepEqual(sanitizeState(value, ids), emptyState()); });
test('favoritos desconhecidos, duplicados e inválidos são ignorados', () => assert.deepEqual(sanitizeState({ favorites: ['a', 'a', null, 'ausente', 'b'] }, ids).favorites, ['a', 'b']));
test('cada filtro inválido recupera seu padrão', () => assert.deepEqual(sanitizeState({ filters: { time: -1, budget: '20', place: 'lua', company: null } }, ids).filters, defaultFilters));
test('filtros sem limite sobrevivem à serialização', () => { const filters = { time: null, budget: null, place: 'fora', company: 'sozinho' }; assert.deepEqual(sanitizeState(JSON.parse(JSON.stringify({ filters })), ids).filters, filters); });
test('histórico ignora referências removidas, datas inválidas e IDs repetidos', () => { const entry = { id: '1', activityId: 'a', date: '2026-09-27T15:00:00.000Z' }; assert.deepEqual(sanitizeState({ history: [entry, entry, { ...entry, id: '2', activityId: 'x' }, { ...entry, id: '3', date: 'ontem' }, null] }, ids).history, [entry]); });
test('mesma atividade em momentos diferentes permanece, mais recente primeiro', () => { const older = { id: '1', activityId: 'a', date: '2026-09-26T12:00:00.000Z' }; const newer = { id: '2', activityId: 'a', date: '2026-09-27T12:00:00.000Z' }; assert.deepEqual(sanitizeState({ history: [older, newer] }, ids).history, [newer, older]); });
test('favoritos, filtros e histórico são recuperados juntos', () => { const state = { ...emptyState(), favorites: ['b'], history: [{ id: '1', activityId: 'a', date: '2026-09-27T12:00:00.000Z' }] }; assert.deepEqual(sanitizeState(JSON.parse(JSON.stringify(state)), ids), state); });
